import { useState } from 'react';
import { ChevronLeft, ChevronRight, Plus } from 'lucide-react';
import type { Context } from './shared';
import { InterviewList } from '../components/InterviewList';
import { addDays, localDate, today } from '../utils/dates';
import { interviewDate, interviewTime, localTimezone, sortedInterviews } from '../utils/interviews';
export function Calendar({ctx}: {ctx: Context}) {
  const [month,setMonth] = useState(() => today().slice(0,7));
  const [selected,setSelected] = useState(today());
  const [showCancelled,setShowCancelled] = useState(false);
  const first = new Date(month+'-01T12:00:00');
  const gridStart = addDays(localDate(first),-first.getDay());
  const appointments = sortedInterviews(ctx.data.interviews.filter(i => showCancelled || i.status !== 'Cancelled'));
  const move = (offset: number) => { const d = new Date(first); d.setMonth(d.getMonth()+offset); setMonth(localDate(d).slice(0,7)); setSelected(localDate(d)); };
  return <><section className="card calendar-card"><div className="section-heading calendar-heading"><div><h2>{first.toLocaleDateString([], {month:'long',year:'numeric'})}</h2><p>Appointments · {localTimezone()}</p></div><div className="calendar-tools"><button className="icon-button" aria-label="Previous month" onClick={() => move(-1)}><ChevronLeft size={18}/></button><button className="button secondary" onClick={() => {setMonth(today().slice(0,7));setSelected(today());}}>Today</button><button className="icon-button" aria-label="Next month" onClick={() => move(1)}><ChevronRight size={18}/></button><button className="button primary" onClick={() => ctx.edit({type:'interview',date:selected})}><Plus size={16}/>Add appointment</button></div></div>
    <div className="calendar-scroll"><div className="calendar-grid">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d => <div className="calendar-weekday" key={d}>{d}</div>)}{Array.from({length:42},(_,n) => {const date = addDays(gridStart,n);const items=appointments.filter(i => interviewDate(i) === date);return <div key={date} className={`calendar-day ${date.slice(0,7)!==month ? 'outside-month' : ''} ${date===selected ? 'selected-day' : ''} ${date===today() ? 'current-day' : ''}`}><button className="calendar-date calendar-day-add" aria-label={`Add appointment on ${date}`} title="Add an appointment" aria-pressed={date===selected} onClick={() => { setSelected(date); ctx.edit({type:'interview',date}); }}><span className="calendar-day-number">{Number(date.slice(-2))}</span><span className="sr-only">{items.length} appointments</span></button>{items.slice(0,3).map(i => {const job=ctx.data.jobs.find(j => j.id===i.job_id);return <button key={i.id} className={`calendar-event ${i.status !== 'Scheduled' ? 'event-inactive' : ''}`} title={`${job ? job.company + ' · ' + i.stage : i.title || 'Appointment'} · ${i.status}`} onClick={() => ctx.edit({type:'interview',job,interview:i})}><strong>{interviewTime(i)} · {job?.company || i.title || 'Appointment'}</strong><span>{job ? i.stage : i.format}</span></button>;})}{items.length>3 && <button className="text-button calendar-more" onClick={() => setSelected(date)}>+{items.length-3} more</button>}</div>;})}</div></div><div className="calendar-footer"><span>Click anywhere in a day square to add an appointment. Click an appointment to edit it.</span><label className="check-label"><input type="checkbox" checked={showCancelled} onChange={e=>setShowCancelled(e.target.checked)}/>Show cancelled</label></div></section>
    <section className="card calendar-agenda"><div className="section-heading"><div><h2>{new Date(selected+'T12:00:00').toLocaleDateString([], {weekday:'long',month:'long',day:'numeric',year:'numeric'})}</h2><p>Appointments for the selected day</p></div><button className="text-button" onClick={() => ctx.edit({type:'interview',date:selected})}><Plus size={16}/>Add appointment</button></div><InterviewList items={appointments.filter(i => interviewDate(i)===selected)} ctx={ctx}/></section></>;
}
